language: python
python:
  - "3.6"
sudo: false
cache: pip

notifications:
  slack: lisvai:SgdQxglgGWYCyiAAWa3aU5Pg

before_install:
  # - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip nose numpy scipy scikit-learn
  - source activate test-environment
  - pip install codecov pep8 python-coveralls flake8
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package simple_esn --logging-level=INFO
  - flake8

after_success:
  - coveralls --config_file .coveragerc
  - codecov
